name: Java CI with Maven

on:
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  test:
    uses: FontysVenlo/alda-workflows/.github/workflows/maven.yml@main
    permissions:
      checks: write
      contents: read
      pull-requests: write
    secrets: inherit